### PR TITLE
Adding geneirc vue dynamic star rating component

### PR DESCRIPTION
**Pull request by JonathanDn**
Contributed a highly customizable, dynamic and generic vue star rating component

### CODE REVIEW

**Comment by shlomif** [comment]
@JonathanDn : 1. resolve the conflicts. 2. "A highly dynamic vue stars rating component, like google play rating" that should be "A dynamic stars rating component for vue, similar to Google Play’s rating". 3. Get rid of the emoji stars (" ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ") because none of the other entries have them, and people may think we are endorsing this.

Thanks!

**Comment by JonathanDn** [comment]
- Removed the 5 stars as requested
- Edited the title according

Thans for the feedback!

**Comment by lirantal** [comment]
@JonathanDn great.
Do you know how to handle the README file conflict resolution or need my help?

**Comment by JonathanDn** [comment]
I kind of missed it, did not actually know how to do it here via github - but learnet now, from what I saw there were 2 more repos that were added after the one I added, so I organzied all three total by the format.

Let me know if anything needs further adjusting from my side

**Pull request merged**
