### PR TITLE
Add Merlinn to the main README.md

### PR DESCRIPTION
**Pull request by david1542**
We've open-sourced our product, Merlinn (https://merlinn.co/), and wanted to add it to this awesome repo :)

### CODE REVIEW

**Comment by lirantal** [comment]
That looks amazing. Congrats!

**Review by lirantal — COMMENTED** [review]
LGTM

**Comment by david1542** [comment]
@lirantal thanks! I see I don't have permissions to merge :) Can u merge it? 🙏

**Comment by lirantal** [comment]
Yes of course. Got sidetracked on something else :-)

**Pull request merged**
