### PR TITLE
Added a sample Microsoft Israel Open Source Projects

### PR DESCRIPTION
**Pull request by aribornstein**
Added following open source projects developed in Israel

* [VoTT](https://github.com/Microsoft/VoTT) - provides end to end support for generating datasets and validating object detection models from video and image assets.
* [pyNeurboParser](https://github.com/aribornstein/pyNeurboParser) - Semantic Dependency Parsing (SDP) is the task of recovering sentence-internal predicate–argument relationships for content words in text. This software provides a python wrapper and docker enviorment for the NeurboParser semantic dependency parser library, to enable easier usage.
* [Presidio](https://github.com/microsoft/presidio) - Context aware, born to the cloud, customizable data loss prevention service (DLP)
* [Ibex Dashboard](https://github.com/Azure/ibex-dashboard) - dashboarding application that enables building dashboard and templates. It mainly supports Application Insights but data sources and visual components are easily extendable.
* [Secure SaaS Wallet](https://github.com/Azure/Secured-SaaS-Wallet) - consists of the infrastructure Core modules needed for implementing a SaaS cryptocurrency virtual wallet
* [ULIS](https://github.com/Microsoft/Universal-Language-Intelligence-Service) - A framework for supporting multi language intent classification with LUIS and Translate
* [TagAnomaly](https://github.com/Microsoft/TagAnomaly) - a tool for creating labeled data for anomaly detection models. It allows the labeler to select points on a time series, further inspect them by looking at the behavior of other times series at the same time range, or by looking at the raw data that created this time series.

### CODE REVIEW

**Comment by lirantal** [comment]
I see that some (maybe most) were created by the local community, but I don't want to start adding all of MS open source projects because that's not the point. Could you update the list to include just those from the specific orgs for individuals? such as https://github.com/aribornstein/pyNeurboParser 
Perhaps this too https://github.com/Microsoft/TagAnomaly/ and like it.

Not sure. What do others think?

**Comment by lirantal** [comment]
Also, to land a PR faster its better if you separate some of the things here to different PRs that will have less "issues" and we can land them faster. Like adding you as an individual and the projects directly associated with you.

**Comment by aribornstein** [comment]
Hey thanks for the feedback. The point wasn't to add just any Microsoft open source projects the goal was to add all the projects created in Israel. Each of these projects I was directly involved in and were created in collaboration with Israeli start ups for the local ecosystem thats why i shared them does that make sense?

**Comment by lirantal** [comment]
Sounds good, I resolved the conflicts.

Looking now at the projects list though it's hard to find and figure out why projects are there.
I'm wondering if we should perhaps build it in a different way so that we have a table with projects listed and in another column the owner for the project as a contact. This will make more sense and allow connecting people and projects.

Perhaps it won't block this PR from landing but could be a good issue to handle.
WDYT?

**Comment by aribornstein** [comment]
I think it could be cool to organize the projects using some sort of categorization as the list grows I'll try to think of something.

**Comment by UrielOfir** [comment]
@lirantal,
Do you think we should close this PR?

**Comment by lirantal** [comment]
Yes, been open for a while. Let's close and re-evaulate that again if OP wants to engage again.
Thanks Uriel!

**Pull request closed without merging**
