### PR TITLE
docs: add raptor to the list :)

### PR DESCRIPTION
**Pull request by AlmogBaku**

### CODE REVIEW

**Comment by UrielOfir** [comment]
Thank you for your contribution :)

Please fix your PR.

You add your project to the list without keeping the alphabetical order.

**Comment by AlmogBaku** [comment]
done

**Comment by AlmogBaku** [comment]
just making sure - only the list of contributor is alphabetical right?

**Comment by UrielOfir** [comment]
The projects list is also alphabetical.

**Comment by AlmogBaku** [comment]
ok, i think it passing the tests now

**Comment by UrielOfir** [comment]
Another fix you need to do is to put the stars badge of Liran's project in his line.
Now your project have his stars badge.

Thank you for your patience.

**Comment by AlmogBaku** [comment]
good catch!

**Comment by UrielOfir** [comment]
We did it!
Thank you.

**Pull request merged**
