### PR TITLE
add rluvaton open source projects

### PR DESCRIPTION
**Pull request by rluvaton**
I love open source

### CODE REVIEW

**Comment by UrielOfir** [comment]
Hi Raz, thank you for your contribution.
Please add to the projects you add to the list - the last commit badge, and top-language badge.

There is a mistake in the alphabetic order of the lists. Can you check it?

**Comment by UrielOfir** [comment]
Hi @rluvaton, are you planning to fix the PR?

**Comment by rluvaton** [comment]
Hey, yes I'm just swamp right now, will try to get to it later today

**Comment by rluvaton** [comment]
@UrielOfir fixed

**Pull request merged**
