### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AmosSzust**
Added WhatsNext open source project

### CODE REVIEW

**Review by lirantal — CHANGES_REQUESTED** [review]
@AmosSzust happy to add but can we consolidate these to be in one entry?

**Comment by AmosSzust** [comment]
Consolidated, thanks :)

**Comment by AmosSzust** [comment]
Fixed the issue, I hope.

**Comment by lirantal** [comment]
Yes @AmosSzust, thank you! I added a little touch up to make it a bit more clear.

**Pull request merged**
