### PR TITLE
chore: added 2 tomerfi projects, auto-me-bot and tomfi-archetypes

### PR DESCRIPTION
**Pull request by TomerFi**

### CODE REVIEW

**Comment by TomerFi** [comment]
CI failures are addressed in #162 .
This PR will be rebased and un-drafted after the aforementioned one gets merged.

**Comment by UrielOfir** [comment]
Can you do a new commit after merging the current 'master' branch?

**Comment by UrielOfir** [comment]
Thank you for your contribution :)

**Comment by TomerFi** [comment]
Thank you very much @UrielOfir .

**Pull request merged**
