### PR TITLE
Check lists alphabetical order + some maintenance

### LINKED ISSUE #105: Reorder the lists alphabetically and check it in a CI workflow
1. reorder the lists alphabetically
2. add a markdown linter that checks for this as part of a CI
3. update the [contribution guide](https://github.com/lirantal/awesome-opensource-israel/blob/master/CONTRIBUTING.md#contribution-guidelines) accordingly

_Originally posted by @lirantal in https://github.com/lirantal/awesome-opensource-israel/issues/104#issuecomment-1416858998_

### PR DESCRIPTION
**Pull request by jond01**
Resolves #105.

Changes (in sync with the commits):
- [x] Add a Python script that 
- [x] Add a GitHub workflow (CI/tests)
- [x] Check for failure before sorting the lists:
  https://github.com/jond01/awesome-opensource-israel/actions/runs/4106618488/jobs/7085077681#step:4:21
  https://github.com/jond01/awesome-opensource-israel/pull/1
- [x] Order the lists alphabetically. The test passes:
  https://github.com/jond01/awesome-opensource-israel/actions/runs/4106874906/jobs/7085652772#step:4:1
- [x] Update the contrib. guide
- [x] Trim trailing whitespaces
- [x] Remove duplicate companies - Amplication and Logz.io (d83b160521a56b5b33ad94e703e0642977e796e9).
  When viewing the total changes, the two removed lines are these.

### CODE REVIEW

**Comment by lirantal** [comment]
Looks ready to merge. We good @jond01 or were you thinking to make any other changes?

**Review by lirantal — APPROVED** [review]

**Comment by jond01** [comment]
I forgot to write - there's just one thing:
Can you please enable GitHub actions on the repo settings? 
The workflow doesn't run here - it does run and pass on my mirror: https://github.com/jond01/awesome-opensource-israel/pull/1.

**Comment by lirantal** [comment]
It's ready and enabled, it will run once we merge and then we can iterate.
I'll go ahead and land this.

**Comment by lirantal** [comment]
See here: https://github.com/lirantal/awesome-opensource-israel/actions/runs/4116810199

**Comment by UrielOfir** [comment]
Hey @jond01, thank you so much for your contribution! I am interested in furthering the development of this repository, and I'd love to collaborate with you. Would you be available to connect via LinkedIn or Facebook so we can discuss further? Let me know!

**Comment by jond01** [comment]
Great to hear that Uriel 😄
And sure, I've just sent you a LinkedIn connection request

**Pull request merged**
