### PR TITLE
Added myself, and some other stuff

### PR DESCRIPTION
**Pull request by benjamingr**
- Add myself, I'm core @ node, bluebird, mobx, lolex and a bunch of other stuff
 - Add Peer5, we maintain videojs-contrib-hls.js which has adds hls.js on top of video.js and has a lot of monthly downloads, we also actively maintain help maintain sinon, ioredis and a bunch of other open source projects.
 - Alphabetize contributor list.

### CODE REVIEW

**Comment by benjamingr** [comment]
Also, instead of:

> Always add your items to the end of a list. To be fair, the order is first-come-first-serve.

I alphabetized it - feel free to revert that.

**Comment by lirantal** [comment]
Looks good.

@benjamingr what do you think about having a table for the individuals list where it says what an individual is known for? I'm pretty sure this will be very interesting for readers. For example, right now no one knows you're a core @nodejs contrib, so the list of open source actively involved individuals is kind of out of context.

**Comment by benjamingr** [comment]
>  For example, right now no one knows you're a core @nodejs contrib, so the list of open source actively involved individuals is kind of out of context.

Sure, a 'projects involved in' field makes sense - though I'm not in favor of" rating" people (or their contribution). I think we should take anyone here (and let people define how they contribute) and list contributions and companies.

I would also put people over companies and projects below (with projects with ~ <100K downloads last). I would try to include _as many people and projects_ as possible and to make as many people feel a part of this.

**Comment by lirantal** [comment]
Good stuff 👍

**Comment by benjamingr** [comment]
@lirantal do you know what anyone currently written does?

I'd:

 - filter projects by #github stars 
 - include all forms of contribution (not just authoring a package)
 - try to include as many people as possible.

**Comment by lirantal** [comment]
@benjamingr for people currently on the repo list - yeah I do - either I added them or we can find it in the PRs that were made.

I am totally for making a more visible list of Israeli open source contributors, but I don't want to scrape anything or pull in the same list from github and put it here. It loses the whole point of a curation IMO.
I agree with adding any sort of contribution, including as many as possible, and definitely not try to rate people - I want people to open the PRs and add others or themselves.

**Pull request merged**
