### PR TITLE
Add individual

### PR DESCRIPTION
**Pull request by fujifish**

### CODE REVIEW

**Comment by lirantal** [comment]
I will hold on this PR as I think we need a "known for" extension to the individuals list so their impact on opensource is clear

**Comment by fujifish** [comment]
No problem.

**Comment by OriHoch** [comment]
I think individuals is indeed a problem, because any definition will leave someone out..
maybe only for historical figures

unless you define it just as "people that have more then X contributions on GitHub per week"

**Comment by lirantal** [comment]
@OriHoch agree that it's not going to be science-level of how we factor who to approve or decline, but I think if you weigh a two people it should be fairly easy to figure out. Worst case we can have votes or something in place. This is why I wanted to add a 'known for' column or something like this, to help readers get a context of how and in which areas the individual has made impact.

Also the thing about awesome lists is that they are awesome. If the bar is low and we just create a list of everyone then we're missing the point.

**Comment by lirantal** [comment]
Closing for now

**Comment by benjamingr** [comment]
I would also recommend removing "individuals" and focusing on organizations and communities.

Individuals encourages micro-celebritism which is kinda toxic.

**Comment by lirantal** [comment]
Yes, agree and can see how it leads to that. However my intent wasn't about "showing off" but rather about a sort of contact book for folks in Israel whom are involved in open source, and to capture the type of projects/tech they are involved with to further help networking and to collaborate locally. It isn't a leaderboard and not an exclusive list either way. Simply, if someone is doing open-source, call them out and the work they do.

**Pull request closed without merging**
